name: Environment Based CI

on:
  push:
    branches:
      - main
      - staging
      - dev
      - feature/**

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Select Environment URL
        id: set-env
        run: |
          if [[ "${GITHUB_REF}" == "refs/heads/main" ]]; then
            echo "BASE_URL=${{ secrets.PROD_URL }}" >> $GITHUB_ENV
          elif [[ "${GITHUB_REF}" == "refs/heads/staging" ]]; then
            echo "BASE_URL=${{ secrets.STAGING_URL }}" >> $GITHUB_ENV
          else
            echo "BASE_URL=${{ secrets.DEV_URL }}" >> $GITHUB_ENV
          fi

      - name: Run tests
        run: pytest tests -v
        env:
          BASE_URL: ${{ env.BASE_URL }}